export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const POSTS_DATA_FETCHED = "POSTS_DATA_FETCHED";
export const ADD_POSTS_REQUEST = "ADD_POSTS_REQUEST";
export const POST_ADDED = "POST_ADDED";
export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const POST_DATA_FETCHED = "POSTS_DATA_FETCHED";